apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: hello-world
  name: hello-world
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: hello-world
  type: LoadBalancer
status:
  loadBalancer: {}
